### PR TITLE
chip-seq: new package

### PR DESCRIPTION
**Pull request by gio31415**

### CODE REVIEW

**Comment by gio31415** [comment]
@alalazo

**Review by rmsds — APPROVED** [review]

**Review by rmsds — CHANGES_REQUESTED** [review]
Actually I just noticed that this code doesn't actually build with the intel compiler because of the following line in the Makefile:
```
CC = gcc
```
I guess we should probably add something like:
```
conflicts('%intel')
```

**Comment by alalazo** [comment]
@rmsds @gio31415 What if instead of adding a conflict we'll try to edit the Makefile to change the compiler? Or is `chip-seq` relying on any GCC extension that is not available elsewhere?

**Comment by gio31415** [comment]
The chip-seq package does not depend on particular GCC-dependent extensions.

**Comment by gio31415** [comment]
Should we remove the CC = gcc line in the makefile?

**Comment by gio31415** [comment]
Actually, the chip-seq code compiles correctly with the following CFLAGS and LDFLAGS specs:

CFLAGS = -O3 -std=gnu99 -W -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
LDFLAGS = -O3 -std=gnu99 -fPIC -lm

the -std=gnu99 C Language option being essential for correct compilation.
What would you suggest for the package building on SCITAS? Is the Intel compiler compatible with this GCC option?

**Comment by alalazo** [comment]
> the -std=gnu99 C Language option being essential for correct compilation.

Are you getting errors if you change the option to `-std=c99`?

**Comment by gio31415** [comment]
Finally, I just had to modify the Makefile in order to change the compiler:
makefile.filter('CC = .*', 'CC = ' + env['CC'])

The -std=gnu99 option seems to work with the Intel compiler (icc) as well. I've checked it on my branch.
I pushed the new package version to the main releases/paien branch.
You should now be able to test it again.
Thanks a lot for your help and advice! :-)

**Review by rmsds — APPROVED** [review]
Looks good and builds with our supported compilers.

**Pull request merged**
