### PR TITLE
new package: sicer (round 2)

### PR DESCRIPTION
**Pull request by rmsds**
QA doesn't like my branch name on #204

### CODE REVIEW

**Comment by rmsds** [comment]
I went with the spack builtin set_executable().

I found it when investigating why stat didn't work, stat was actually overridden by a spack builtin within the class.

**Review by nrichart — APPROVED** [review]
seems ok now :)

**Review by alalazo — APPROVED** [review]
LGTM from the perspective of code in package.py. For what is actually done, I trust you already did some basic checks and feel the pain of what you went through here.

**Review by alalazo — APPROVED** [review]
LGTM from the perspective of code in package.py. For what is actually done, I trust you already did some basic checks and feel the pain of what you went through here.

**Pull request merged**
